eZTest:
    pattern: /test/{contentId}
    defaults:
        _controller: eZDemoBundle:Demo:test
        contentId: 102
    requirements:
        contentId: \d+

eZTestWithLegacy:
    pattern: /test/legacy/{contentId}
    defaults:
        _controller: eZDemoBundle:Demo:testWithLegacy
        contentId: 102
